export default {
  // Session
  CHANGE_AUTH_TAB: 'CHANGE_AUTH_TAB',

  // User
  REQUEST_USER_LOGIN: 'request_user_login',
  REQUEST_SIGN_UP: 'request_sign_up',
  REQUEST_RECOVER_PASSWORD: 'request_recover_password',
  REQUEST_FACEBOOK_LOGIN: 'REQUEST_FACEBOOK_LOGIN',
  RECEIVE_USER: 'RECEIVE_USER',
  USER_LOGOUT: 'USER_LOGOUT',
  CHECK_LOGIN: 'CHECK_LOGIN',
  USER_NOT_ENTERED: 'USER_NOT_ENTERED',
};
